
from datetime import datetime

def generate_report(url, header_results, cookie_results):
    """
    Generates a markdown security report from scan results.

    Parameters:
    ----------
    url : str
        The target URL that was scanned.
    header_results : list[dict]
        Output from check_headers()
    cookie_results : list[dict]
        Output from check_cookies()

    Returns:
    -------
    str
        A formatted markdown string containing the full report.
    """
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    high_issues = [r for r in header_results if r["severity"] == "HIGH"]
    medium_issues = [r for r in cookie_results if r["severity"] == "MEDIUM"]
    total_issues = len(high_issues) + len(medium_issues)

    lines = []

    # Header
    lines.append(f"# DigSecure Scan Report")
    lines.append(f"")
    lines.append(f"| | |")
    lines.append(f"|---|---|")
    lines.append(f"| **Target** | {url} |")
    lines.append(f"| **Scan Date** | {now} |")
    lines.append(f"| **Total Issues** | {total_issues} |")
    lines.append(f"")

    # Security Headers
    lines.append(f"---")
    lines.append(f"")
    lines.append(f"## 🔴 HIGH — Missing Security Headers")
    lines.append(f"")
    lines.append(f"| Header | Status | Risk |")
    lines.append(f"|--------|--------|------|")
    for r in header_results:
        status = "✓ PASS" if r["present"] else "✗ MISSING"
        risk = r["description"] if not r["present"] else "—"
        lines.append(f"| {r['header']} | {status} | {risk} |")
    lines.append(f"")

    # Cookie Audit
    lines.append(f"---")
    lines.append(f"")
    lines.append(f"## 🟡 MEDIUM — Cookie Security Issues")
    lines.append(f"")
    if cookie_results:
        lines.append(f"| Cookie | Flag | Status | Risk |")
        lines.append(f"|--------|------|--------|------|")
        for r in cookie_results:
            status = "✓ PASS" if r["present"] else "✗ MISSING"
            risk = r["description"] if not r["present"] else "—"
            lines.append(f"| {r['cookie_name']} | {r['flag']} | {status} | {risk} |")
    else:
        lines.append(f"No cookies detected.")
    lines.append(f"")

    # Remediation
    lines.append(f"---")
    lines.append(f"")
    lines.append(f"## Remediation")
    lines.append(f"")

    if high_issues:
        lines.append(f"### Missing Headers")
        lines.append(f"")
        for r in high_issues:
            lines.append(f"**{r['header']}**")
            lines.append(f"")
            if r["header"] == "Content-Security-Policy":
                lines.append(f"```")
                lines.append(f"Content-Security-Policy: default-src 'self'; script-src 'self'")
                lines.append(f"```")
            elif r["header"] == "Strict-Transport-Security":
                lines.append(f"```")
                lines.append(f"Strict-Transport-Security: max-age=31536000; includeSubDomains")
                lines.append(f"```")
            elif r["header"] == "X-Frame-Options":
                lines.append(f"```")
                lines.append(f"X-Frame-Options: DENY")
                lines.append(f"```")
            elif r["header"] == "X-Content-Type-Options":
                lines.append(f"```")
                lines.append(f"X-Content-Type-Options: nosniff")
                lines.append(f"```")
            elif r["header"] == "Referrer-Policy":
                lines.append(f"```")
                lines.append(f"Referrer-Policy: strict-origin-when-cross-origin")
                lines.append(f"```")
            elif r["header"] == "Permissions-Policy":
                lines.append(f"```")
                lines.append(f"Permissions-Policy: geolocation=(), microphone=(), camera=()")
                lines.append(f"```")
            lines.append(f"")

    if medium_issues:
        lines.append(f"### Cookie Flags")
        lines.append(f"")
        lines.append(f"Set HttpOnly, Secure, and SameSite flags on all session cookies:")
        lines.append(f"")
        lines.append(f"```")
        lines.append(f"Set-Cookie: session_id=abc123; HttpOnly; Secure; SameSite=Strict")
        lines.append(f"```")
        lines.append(f"")

    # Footer
    lines.append(f"---")
    lines.append(f"")
    lines.append(f"*Generated by DigSecure — For authorized testing only*")

    return "\n".join(lines)